### ISSUE TITLE
How can I make markdoc with Next.js work like mdx with Next.js?

### ISSUE THREAD

**Issue by francisfeng** [markdoc/markdoc#107]
### What happened?

I set up a demo repo for my purpose in here: [markdoc-nextjs-demo](https://github.com/francisfeng/markdoc-nextjs-demo).

From what I understand, `@markdoc/next.js` transforms markdown files into React components. So I should be able to `import` a md file and treat it as a React component in any place suitable, just like the way `@next/mdx` works.

Just like this:
```jsx
// pages/getting-started.js

import MarkdownComponent from '../components/getting-started.md';

export default function GettingStarted(props) {
  return (
    <>
      <header>This is header</header>
      <main>
        <MarkdownComponent></MarkdownComponent>
      </main>
      <footer>This is footer</footer>
    </>
  );
}

```

But when I did that, an error occurred.

```
Server Error
TypeError: Cannot read properties of undefined (reading 'content')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

<img width="989" alt="CleanShot 2022-06-27 at 22 22 40@2x" src="https://user-images.githubusercontent.com/1040288/175964105-9c7fd35c-6477-4508-b949-9f372f7d6da8.png">
 
The documentation on [Next.js Layout](https://markdoc.io/docs/nextjs#layouts) does not have the same use case. I want to apply additional layouts in other routes other than App.component.

Is there another way to achieve this?

### To reproduce

Demo repo [markdoc-nextjs-demo](https://github.com/francisfeng/markdoc-nextjs-demo).

### Version

0.1.4

**Comment by mfix-stripe** [comment]
@francisfeng you need to pass in the props from `pageProps` (as [demonstrated here](https://github.com/markdoc/docs/blob/main/pages/_app.js#L195))

```jsx
<Component {...pageProps} />
```

**Comment by francisfeng** [comment]
> @francisfeng you need to pass in the props from `pageProps` (as [demonstrated here](https://github.com/markdoc/docs/blob/main/pages/_app.js#L195))
> 
> ```js
> <Component {...pageProps} />
> ```

I think it’s a little more than that. As you can see in my [`_app.js`](https://github.com/francisfeng/markdoc-nextjs-demo/blob/5d275379a3bd5d37348c294d679d22c40212774a/pages/_app.js#L4), if I open `localhost:3000`, the console will print out an empty object with `pageProps`. 

**These is no `markdoc` property in `MyApp` component.**

```jsx
// _app.js
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  console.log(pageProps)
  return <Component {...pageProps} />
}

export default MyApp
```

But if I change `index.js` to `index.md`, now the console will print out an object with `markdoc` property.

The thing is I want `index.js` instead of `index.md`.

**Comment by johnlindquist** [comment]
I'm in the same situation. 

My current workaround:

In `_app.tsx`:

```tsx
function MyApp({ Component, pageProps }: AppProps) {
  // Check if it's loading a .md file:
  if ("markdoc" in pageProps) {
    // add <Layout>, etc wrappers/logic:
    return (
      <MyLayout>
        <Component {...pageProps} markdoc={pageProps} />
      </MyLayout>
    )
  }

  // My other pages can handle layout logic, etc in their `index.tsx` files:
  return <Component {...pageProps} markdoc={pageProps} />
}


```
