### ISSUE TITLE
Doesn't work w JS disabled

### ISSUE THREAD

**Issue by brianleroux** [markdoc/markdoc#11]
### What happened?

Expected navigation to work but realized it requires JavaScript to be enabled. There are a number of situations where this can happen. https://technology.blog.gov.uk/2016/09/19/why-we-use-progressive-enhancement-to-build-gov-uk/

### To reproduce

Navigate to site w JS disabled

**Comment by mfix-stripe** [comment]
Hey @brianleroux, thanks for posting. Unfortunately, our site is using a lot of systems that rely on JavaScript to run. Hopefully Next.js supports better no-script support for routing in the future, but until then we are stuck with what we have. 
Appreciate the helpful idea, though.
