### ISSUE TITLE
Use registered schema in Next.js validation

### ISSUE THREAD

**Issue by symmb** [markdoc/markdoc#129]
### What happened?

I changed a fresh Next.js started clone in a way that should (as far as I understand) clearly trigger a schema validation error but I didn't get any error from `npm run dev` or `npm run build`. I expected the build to fail both using the `dev` and the `build` script.

### To reproduce

1. Clone the [Next.js starter project](https://github.com/markdoc/markdoc-starter/tree/cf36368f405a41499aded8b61b136c0bda44c0e3) and install dependencies using `npm install`
2. Modify the `callout` tag to only allow paragraphs as children

```diff
export const callout = {
   render: Callout,
   description: 'Display the enclosed content in a callout box',
-  children: ['paragraph', 'tag', 'list'],
+  children: ['paragraph'],
   attributes: {
     title: {
       type: String,
```

3. Start the development server with `npm run dev` and open the page in a browser
4. Nest two callout tags on a page (which should be disallowed)

```
{% callout %}
{% callout %}
This is a full-featured boilerplate for a creating a documentation website using Markdoc and Next.js.
{% /callout %}
{% /callout %}
```

5. The page refreshes with the nested callout tags and no error is shown

You can also add a validation function that always fails to the definition of `callout` which appears to have no effect either.

```js
import {Callout} from '../../components';

export const callout = {
  render: Callout,
  description: 'Display the enclosed content in a callout box',
  children: ['paragraph', 'tag', 'list'],
  attributes: {
    title: {
      type: String,
      description: 'The title displayed at the top of the callout',
    },
  },
  validate(node, config) {
    return [
      {
        id: "my-error",
        level: 'critical',
        message: "This should fail",
      }
    ]
  },
};

```

All of this also applies to nodes.

### Version

0.1.4

### Additional context

The exact commit of the starter repository used is cf36368f405a41499aded8b61b136c0bda44c0e3.

**Comment by mfix-stripe** [comment]
@symmb I'm changing this issue from a bug report to an enhancement, since this is currently working as intended. 

We just need to include the correct config here: https://github.com/markdoc/next.js/blob/main/src/loader.js#L68. 

Previously, I had not included the config there because then it needs to be imported in 2 places, though at this point, I think that is worth it. 

(Cc @matv-stripe)
