### ISSUE TITLE
Search bar support

### ISSUE THREAD

**Issue by jasonbosco** [markdoc/markdoc#13]
First off, thank you for open sourcing this! I'm a big fan and a long-time user of Stripe, mainly because of the extensive developer-friendly docs.

I noticed that the docs don't have a built-in search bar. I work on [Typesense](https://typesense.org/) which is an open source alternative to Algolia / Elasticsearch and I'd love to build a search-bar + scraper integration, similar to the one we have for Docusaurus: https://docusaurus.io/docs/search#using-typesense-docsearch

Would you be open to this?

**Comment by mfix-stripe** [comment]
@jasonbosco glad to hear it! We plan to add docs search in the near future, and I will consider this as an option. 

Going to close this issue, but feel free to weigh in on this discussion in the meantime: https://github.com/markdoc/markdoc/discussions/4

**Comment by rayfoss** [comment]
Here is a Screenshot of a good search UI combined into the navigation menu from a really small app no one has ever heard of. 
![Screenshot_20220512-091020](https://user-images.githubusercontent.com/876076/167967128-52b489a4-b2c4-48ba-b843-fe1f7e753bf5.png)

**Comment by MarcusSorealheis** [comment]
+1 idea of a Search bar, and I would also be open to building whatever is needed to support MongoDB Atlas Search. 

It's not an alternative to Elasticsearch, per se, but it does run on the same sub-system, [Apache Lucene](https://github.com/apache/lucene/), and MongoDB. There's a free tier that will be big enough for almost all companies' docs content and some great open source UI options. We have a lot of robust features and a few more coming that could really supercharge developers experiences of looking for answers in documentation.
