### ISSUE TITLE
Markdoc formatter

### ISSUE THREAD

**Issue by jameshfisher** [markdoc/markdoc#145]
I need to write a script that modifies Markdoc files. Specifically, it will add an `id` attribute to nodes that do not yet have one. For example, given the file:

```
# Debugging

# Running {% #running %}
```

I want to modify the file to:

```
# Debugging {% #d3adb33f %}

# Running {% #running %}
```

(Where `d3adb33f` is some fresh identifier, e.g. a UUID.)

I want to do this transform with a pipeline like

```
input --[Markdoc.parse]--> AST -> --[custom logic]--> AST --[Markdown.stringify]--> output
```

However, I don't see a `Markdoc.stringify`, or a `Node.toString`, or a Markdoc renderer, or anything like that.

**Has anyone written a `Markdown.stringify` or similar? Or could you recommend some other way to achieve my goals?**

**Comment by mfix-stripe** [comment]
@jameshfisher do you really need to write the id to the file though? Or can you just generate the ID at runtime? We currently do this w/ our headings for our docs site https://github.com/markdoc/docs/blob/main/markdoc/nodes/heading.markdoc.js#L27

**Comment by jameshfisher** [comment]
Thanks for the reply @mfix-stripe. Yep, I do need to write it to the file, because it has to remain stable.

(Btw, I'm looking at using https://github.com/remarkjs/remark instead, because it seems to have a much stronger emphasis on such transformation pipelines. I guess the difficulty in Markdoc is that it builds on markdown-it, which seems to not have any "stringify" feature.)

**Comment by mfix-stripe** [comment]
@jameshfisher we released a new experimental formatter in [v0.1.5](https://github.com/markdoc/markdoc/releases/tag/0.1.5). Please give it a try and let us know if you run into bugs.

**Comment by mfix-stripe** [comment]
@jameshfisher have you had a chance to try out the formatter yet? Have you run into any bugs?

**Comment by mfix-stripe** [comment]
Going to close out this issue, with the existence of https://github.com/markdoc/markdoc/blob/main/src/formatter.ts.

If folks run into issues with the formatter (as I am sure there are still bugs), please open a new issue 👍.
