### ISSUE TITLE
Markdoc docs broken on Firefox for Android

### ISSUE THREAD

**Issue by rayfoss** [markdoc/markdoc#16]
### What happened?

I visited the docs website and could only see about 5 pages. Turns out the navigation bar has broken breakpoint or broken Firefox support... There is no way to make it show without going into Desktop mode.

I found it quite bizarre that a documentation framework had such bare bones documentation... Until I received a link to the FAQ from @mfix-stripe and realized, 99% of the docs were not showing up for me.

![Screenshot_20220512-075421](https://user-images.githubusercontent.com/876076/167960953-ae4213dd-eb9c-4753-8bbc-2f2d185b2622.png)

### To reproduce

Open on a Pixel 6 Pro with Firefox for Android (It uses the Gecko rendering engine).

### Version

1

### Additional context

I presume it's just a desktop/mobile continuum breakpoint issue... Could be more a more serious presumption that all Mobile browsers run a WebKit based HTML rendering engine, or that all Android phones use V8.

**Comment by mfix-stripe** [comment]
@rayfoss this is actually the correct nav. If you open the site on desktop, you can see that there are two navs: a top on and a left one. We only shop the top nav on mobile. Thanks for writing in!

**Comment by rayfoss** [comment]
That's really poor design... You mean to tell me having the docs on split screen on a laptop will make it impossible to navigate, by design? Why show the navigation bar up top when the menu button is pressed?

Are you friends with the GitHub guy who decided that mobile users should not have a clone button because Termux and SSH don't exist? /s (I love programing on my phone, the tablet is too bright and cumbersome)
