### ISSUE TITLE
docs bug with next.js/tags?

### ISSUE THREAD

**Issue by guidorice** [markdoc/markdoc#227]
### What happened?

I am following through the [next.js + markdoc guide here](https://markdoc.dev/docs/nextjs#built-in-next.js-tags).

```
./markdoc/tags/Next.markdoc.ts:1:45
Type error: Cannot find module '@markdoc/next.js/tags' or its corresponding type declarations.

> 1 | export { comment, head, link, script } from '@markdoc/next.js/tags';
```
Does anyone know if this is an error in the docs, or what the appropriate import statement would be?

### To reproduce

Apply example code from the section "built-in next.js tags".

https://markdoc.dev/docs/nextjs#built-in-next.js-tags

### Version

@markdoc/markdoc@0.1.11

**Comment by guidorice** [comment]
Thanks @mfix-stripe I figured out my issue. I forgot to export the `Next.markdoc.ts` from `markdoc/tags/index.ts`. Here's the fix:

```typescript
/* Use this file to export your markdoc tags */
export * from './callout.markdoc';
export * from './Next.markdoc'; // added this line
```

Do you want me to make an enhancement PR to https://github.com/markdoc/markdoc-starter because this might be a common use case to install those additional tags?

Thanks!

**Comment by mfix-stripe** [comment]
> Do you want me to make an enhancement PR to https://github.com/markdoc/markdoc-starter because this might be a common use case to install those additional tags?

Go for it! Thanks @guidorice 🙏
