### ISSUE TITLE
can't compile next.js starter

### ISSUE THREAD

**Issue by usulpt** [markdoc/markdoc#24]
### What happened?

just cloned the repo, ran `npm install` followed by `npm run dev` and got this error after loading `localhost:3000`

> ./pages/index.md
> C:\github\markdoc\next.js-starter\node_modules\@markdoc\next.js\node_modules\@markdoc\markdoc\dist\index.js:6648
>   return !!value?.$$mdtype;
>                  ^
> 
> SyntaxError: Unexpected token '.'

### To reproduce

npm install
npm run dev

### Version

latest

**Comment by mfix-stripe** [comment]
@usulpt which node version are you using? You probably just need to bump your Node version to 13 or greater. Current Node LTS is version 16 (:

**Comment by usulpt** [comment]
hmm could be, running node 12, gonna try it, thanks
