### ISSUE TITLE
Possible to get contents of tag as string?

### ISSUE THREAD

**Issue by mskri** [markdoc/markdoc#245]
I am attempting to make a custom tag that has a toggle to display node/tags as they render  and to view the raw source without transformations. Tried playing around with `process` and `content` annotations but they seem to only work with fences. Is there a way to get raw content from tag without using fence?

**Comment by rpaul-stripe** [comment]
If you still have the original source string, you can use the `node.lines` property to get the starting and ending line numbers of the corresponding content from the source. Note that this really only works for block-level elements, we don't currently expose the index within the line of inline elements.

You could also try using the experimental Markdoc formatter to programmatically generate Markdoc source for an individual document node. You can use this by calling `Markdoc. __EXPERIMENTAL__format(node)`. This feature is still under active development and we don't recommend using it in production quite yet (hence the unusual method name) but it might be appropriate for your use case.

**Comment by mskri** [comment]
Awesome, I can make it work with those for now! At this point I'm only interested in block-level elements so that limitation doesn't matter.

That `format` function seems neat. Looking forward to it being stable. 👍
