### ISSUE TITLE
Nextjs @emotion wrong styles calculation for nested components

### ISSUE THREAD

**Issue by juanvargas-pax** [markdoc/markdoc#254]
### What happened?

We are implementing `tabs` components according to this example https://markdoc.dev/docs/examples#tabs. 
The Tabs are working fine in a standalone implementation but when we compose with others components breaks the styles (it's seems like the above component it's affecting the `tabs`, Please take a look at the screenshots)

**Note: I tried in an incognito window and the issue persist**
### Screenshots
**Standalone Tabs**
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/85582145/196502482-d1ba7f93-34a6-4b70-8164-93a3273f195d.png">

**Callout** component with Tabs
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/85582145/196502722-be7afb0d-d6d6-483f-a858-d06c541d0690.png">

Tabs and Callout components are not self close components

### To reproduce

1. create a nextjs app
2. create a `Tabs` following this example https://markdoc.dev/docs/examples#tabs
3. add a Callout component on the top

### Version

0.1.3

### Additional context

"@markdoc/markdoc": "^0.1.3",
"@markdoc/next.js": "0.1.9",
"next": "12.2.0",
"prismjs": "^1.29.0",
"react": "17.0.2",
"react-dom": "17.0.2"

**Comment by mfix-stripe** [comment]
@juanvargas-pax I'm going to close this as this just seems like a CSS issue, but please let me know and I can reopen 🙂
