### ISSUE TITLE
Markdown comment syntax results in comment content being rendered

### ISSUE THREAD

**Issue by ReeceHumphreys** [markdoc/markdoc#362]
### What happened?

Comments do not appear to be working correctly. Any text inside of a comment is being rendered.

Ex.)

```md
<!-- This is a comment -->
```

The above comment will be rendered
 

### To reproduce

1. Clone the [markdoc-starter](https://github.com/markdoc/markdoc-starter)
3. Update `docs/index.md` with the following:
```md
---
title: Overview
---

# {% $markdoc.frontmatter.title %}

This is a test

<!-- This is a comment -->
```
4. Run `npm i` then `npm run dev`
5. Navigate to `localhost:xxxx/docs/`
6. The text inside of the comment will be rendered

### Version

0.2.2

### Additional context

<img width="1301" alt="An image showing the comment being rendered" src="https://user-images.githubusercontent.com/14209515/234605097-ebf3ccce-d3fc-48cb-9038-9dc75c62e6c0.png">

**Comment by ReeceHumphreys** [comment]
Did not see the page in the documentation with the notice to pass allowComments: true to Markdoc.Tokenizer. My bad!

**Comment by iloveitaly** [comment]
@ReeceHumphreys what's the best way to pass `allowComments: true` if you are just running something like:

```
const ast = Markdoc.parse(rawMarkdown, { location: true });
```
