### ISSUE TITLE
Emphasis written using `*` without leading and trailing whitespace is incorrectly formatted to use `_`

### ISSUE THREAD

**Issue by emmatown** [markdoc/markdoc#369]
### What happened?

For a Markdoc document like this:

```md
a*b*c
```

The formatter turns it into this:

```md
a_b_c
```

This formatting isn't correct because the underscores won't be interpreted as emphasis, they're just interpreted as text. https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis explains how `_` vs `*` are different.

### To reproduce

1. Create a markdoc document like above
2. Run the formatter on it

### Version

0.2.2

**Comment by rpaul-stripe** [comment]
It looks like markdown-it captures the actual syntax used for emphasis in a `markup` attribute on the token. I'm going to look at preserving that in the AST so we can hopefully reproduce it exactly in the formatter.
