### ISSUE TITLE
Support Next.js 13 app/ directory in @markdoc/next.js

### ISSUE THREAD

**Issue by mfix-stripe** [markdoc/markdoc#378]

**Comment by bradlc** [comment]
Hey @mfix-stripe, we are looking to port a Markdoc Next.js project to app router so are very keen to see support added. Is work on this already planned? If not would you accept a contribution that implemented initial support? Looking at the current implementation I think I could get basic support working on my own, but may need help getting to full feature parity with the pages router implementation.

**Comment by mfix-stripe** [comment]
> Hey @mfix-stripe, we are looking to port a Markdoc Next.js project to app router so are very keen to see support added. Is work on this already planned? If not would you accept a contribution that implemented initial support? Looking at the current implementation I think I could get basic support working on my own, but may need help getting to full feature parity with the pages router implementation.

@bradlc we do not have work planned for this at the moment, so we would love your help with initial support 🙂

**Comment by mfix-stripe** [comment]
Closed with https://github.com/markdoc/next.js/releases/tag/0.3.0
