### ISSUE TITLE
Feature request: validating attribute value with custom `matches` function

### ISSUE THREAD

**Issue by mskri** [markdoc/markdoc#379]
I have been validating attributes with [zod](https://zod.dev/) in the `validate` function.  It would be awesome to be able to define the validation in the attribute definition itself. One option would be to add `validate` function or make the `matches` function return the value of the attribute. You could then use the function to define custom validation in the same place as the attribute itself is declared. It would make it easier to understand what the attribute is and how it should be validated when the declaration and validation are together. 

Yes, you can use RegExp or a list of values to validate the attribute but in some cases that's not enough and it would be better if you could use e.g. zod to do the validation. In some cases the RexExp validation returns error message that isn't useful if you don't understand RexExp. For example if I'm validating that string attribute is not blank using RegExp.

```ts
src: {
  type: String,
  required: true,
  matches: /.+/,
}
```

Resulting error message is `Attribute 'src' must match /.+/. Got '' instead.`. You would have to understand that in RexExp `.+` means "1 or more characters".

**Here's an example of how I would currently do attribute validation with zod**

```ts
export const emailField = {
  render: 'Email',
  children: [],
  attributes: {
    type: {
      type: String,
      required: true,
    },
  },
  validate(node) {
    const errors: ValidationError[] = [];
  
    const email = emailSchema.safeParse(node.attributes.email);
    if (!email.success) {
      errors.push({
        id: 'attribute-value-invalid',
        level: 'error',
        message: "Attribute 'email' has invalid email format",
      });
    }
    
    return errors
  }
};
```

**Here's how I would love to write the validation**

```ts
export const emailField = {
  render: 'Email',
  children: [],
  attributes: {
    email: {
      type: String,
      required: true,
      validation: (value) => {
        const email = emailSchema.safeParse(value);
        if (!email.success) {
          return {
            id: 'image-empty-src',
            level: 'error',
            message: "Attribute 'src' should not be empty.",
          } satisfies ValidationError;
        }
        
        return true;
      },
      errorLevel: 'error'
    },
  }
};
```

PS. What's the purpose of passing `matches(config)`? It includes the whole config and not just the one for the tag.

**Comment by rpaul-stripe** [comment]
I'm open to adding support for this, I don't think there's any real downside in making it possible to define custom validation functions directly on the attribute. One of the reasons we haven't added this yet, however, is that it's possible to achieve this with custom validation types, which are a little bit more powerful.

Here's an example of a parameterized custom validation type that can be used to enable generic Zod validation without having to write a custom function for each attribute:

~~~javascript
import Markdoc from "@markdoc/markdoc";
import { z } from "zod";

function ZodType(schema) {
  return class {
    validate(value, config) {
      const output = schema.safeParse(value);
      if (output.success) return [];
      return output.error.errors.map(({ message }) => ({
        id: "attribute-value-invalid",
        level: "error",
        message,
      }));
    }
  };
}

const config = {
  tags: {
    foo: {
      attributes: {
        bar: {
          type: ZodType(z.string().email()),
        },
      },
    },
  },
};

const example = `
{% foo bar="asdf" %}
This is a test
{% /foo %}
`;

const ast = Markdoc.parse(example);
const errors = Markdoc.validate(ast, config);
console.log(JSON.stringify(errors, null, 4));
~~~

Does something like this meet your needs or do you think we still need a way to define custom validation functions on the schema attribute?

**Comment by rpaul-stripe** [comment]
There was some internal interest in this feature request, so I decided to implement it.

**Comment by mskri** [comment]
> Does something like this meet your needs or do you think we still need a way to define custom validation functions on the schema attribute?

Yes, creating custom type would be sufficient althought a bit more cumbersome than a function where you could check one of types. Didn't even think of extracting it to extracting it to a custom type but I see it would work. 

> There was also some internal interest in this feature request, so I decided to implement it.

Wow, excited to hear that! Looking forward to taking it into use 👍
