### ISSUE TITLE
Duplicate attributes don't create validation errors

### ISSUE THREAD

**Issue by emmatown** [markdoc/markdoc#391]
### What happened?

I expected that having more than one of the same attribute would create a validation error but it doesn't.

I'm not sure if this a bug or not since I imagine there are some use cases where duplicate attributes could be useful (kind of like how multiple classes are allowed) but it at least seems like a strange default to allow multiple of the same attribute and have the last one win.

### To reproduce

```
# a {% #a #b %}
```

### Version

0.3.0

**Comment by rpaul-stripe** [comment]
I've never really considered adding validation here, but it's a good idea. Attributes on a tag correlate directly with properties in the document node's `attributes` object, so adding more than one attribute with the same name to a tag behaves exactly like setting the same property on a JavaScript object more than once—it just overwrites the previous value with a new one. We don't preserve the earlier values in the AST, so there really isn't any legitimate use case for having multiple instances of the same attribute. Classes are special-cased, so they are supported differently.

In the parser's `annotate` function, where we set the attribute value, I think what I should do is have it add an error to the `node.errors` array when it encounters duplicate attribute names. It will still replace the value, so the actual outcome during rendering won't change, but it will result in the user seeing an error during validation.
