### ISSUE TITLE
Confusing error on multiple markdoc sites 

### ISSUE THREAD

**Issue by altosaar** [markdoc/markdoc#41]
### What happened?

@benguz and I need set up a markdoc site for a nonprofit. 

We are getting this cryptic error, and the error message text cuts off strangely: 

C:UsersenjaOneDriveDocumentsGitHub
eactjs.orgeta
ode_modules@markdoc
ext.jssrc
untime.js is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "c:" URIs.

### To reproduce

@benguz followed the quick start docs. 

### Version

Latest 

### Additional context

Deploying on GitHub pages.

**Comment by mfix-stripe** [comment]
Hey @altosaar, could you share a reproduction of this issue? 🙂 Which quick start docs are you referring to?

**Comment by benguz** [comment]
"Using markdoc with next JS" <https://markdoc.io/docs/nextjs> following
steps there and in this starter repo
<https://github.com/markdoc/next.js-starter> (and getting a similar error
with the boilerplate and adding it to an existing next JS site. What would
you us to share as a reproduction?

**Comment by benguz** [comment]
Here is a screenshot of my localhost when I run the next JS starter
repo. [image:
image.png]

**Comment by mfix-stripe** [comment]
@benguz I'm unable to see the image you shared above 🙂

**Comment by benguz** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/84636906/169163736-f0b0376d-57c5-478e-bfec-2fb2615ceb3c.png">
Sorry about that, here it is @mfix-stripe

**Comment by mfix-stripe** [comment]
@benguz I just tried a fresh clone and install of https://github.com/markdoc/next.js-starter, and it is working for me. What operating system are you on? Windows? 

Also have you made any local changes?

**Comment by benguz** [comment]
No local changes and I'm on Windows.

**Comment by colinjnash** [comment]
Having the same issue with the quickstart docs.

**OS:** Windows 11 Home 21H2

![image](https://user-images.githubusercontent.com/24720932/169193299-696893c6-e177-47aa-9246-796cc50e0da3.png)

Also getting a dependency error from the CLI:

![image](https://user-images.githubusercontent.com/24720932/169193477-18ed5c2f-2e08-4841-85a4-91eb27102140.png)

Things seem to point to some sort of issue with Next and Webpack? Either way, I just wanted to second the error that @benguz had.

**Comment by mfix-stripe** [comment]
@benguz @colinjnash which Node version are you using?

**Comment by mfix-stripe** [comment]
Ahh I see, I think this is an issue with Webpack not being able to understand the absolute path on windows, since it starts with `C:`. 

This is probably something we have to fix in https://github.com/markdoc/next.js. Will take a look, but if you have suggested solutions @benguz @colinjnash, please share them 🙂

**Comment by cnashunity** [comment]
@mfix-stripe I see the incorporated fix with `this.resolve`. Thanks for the quick catch and I'll try and validate ASAP.

**Comment by mfix-stripe** [comment]
@cnashunity @benguz @colinjnash just published `@markdoc/next.js@0.1.4-0`. If you install that version instead, does that fix the issues you were seeing?

**Comment by colinjnash** [comment]
Hi @mfix-stripe . Same error again, except the trace dependency is now gone.

![image](https://user-images.githubusercontent.com/24720932/169408176-84b3530b-73fa-4c82-8e81-8ae622c8ab56.png)

Verified package installation outside of Windows with Vercel (docs/concept.md being the validation file):

![image](https://user-images.githubusercontent.com/24720932/169409697-e76c6192-caec-4129-b2d7-f024a621602b.png)

I also confirmed that `yarn build` also fails. I was wondering if it might just be scoped to `dev`.

In the meantime, I might work on creating a Ubuntu WSL dev environment. Is there any way that markdoc might be okay running on an earlier webpack?  Or should I look into using a [custom webpack.config.js](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) and declare explicit paths for the dev build?

**Comment by mfix-stripe** [comment]
@colinjnash that error looks different to me… slightly improved. There is just some issue with Webpack not finding the path using an absolute path on Windows, because it starts with `C:`. Have you ran into this before? 

What happens when you run the tests for https://github.com/markdoc/next.js? 

And yes, it makes sense that it works on Vercel since they don't use Windows environments

**Comment by mfix-stripe** [comment]
I recreated some other Windows errors here (https://github.com/markdoc/next.js/runs/6515621039?check_suite_focus=true) so I should be able to make progress on this from my Mac.

**Comment by colinjnash** [comment]
Hi @mfix-stripe,

Haven't seen any URI path errors since early webpack days. I did find this recently on URI-JS: https://githubmemory.com/repo/react-cosmos/react-cosmos/issues/1332

Unfortunately I'm a little rusty on node and new to next.js, so this might be out of my scope. Wanted to put it there in case it gave more context.

**Comment by mfix-stripe** [comment]
@colinjnash does installing [`0.1.4-1`](https://github.com/markdoc/next.js/releases/tag/0.1.4-1) update the errors for you?

**Comment by colinjnash** [comment]
@mfix-stripe confirmed as working. Thanks so much for the fast fix!

**Comment by mfix-stripe** [comment]
@colinjnash glad to hear it! 🙌

**Comment by Siumauricio** [comment]
I'm getting like almost the same error when I run Next-starter repo, I'm pretty sure is related about webpack config, 
Error when I run Next-example 
![image](https://user-images.githubusercontent.com/47042324/173267101-7837bbf6-d6b4-4e48-b2fd-7f2c19f4f4f7.png)



I be run the test and prints some errors.
![image](https://user-images.githubusercontent.com/47042324/173266911-f7cdc50e-d68a-4174-b7c7-b68b2360fe5f.png)
