### ISSUE TITLE
Markdoc Language Server:

### ISSUE THREAD

**Issue by louiss0** [markdoc/markdoc#429]
### What happened?

I finally managed to get the config working but found some strange errors. I don't know what is happening but it seems like children doesn't work the way it's supposed to. 

### To reproduce

1. Clone this repo https://github.com/louiss0/dummy-markdoc-2
2. go to `intro.mdoc` 
3. Press Ctrl + Shift + U 
4. Look into the terminal for the language server output and you should see the error

If you have error lens installed then you can see the errors in the file.

### Version

0.30.0

**Comment by louiss0** [comment]
I have managed to fix some of them but I just keep getting the error invalid attribute when I write frontmatter. 

When I write a dl tag that looks like this. 

```md
{% dl %}
{% dt "name" /%}{% dd "a description of an entity that is unique to it's form and characteristics" /%}

{% dt "signal" /%}{% dd "a reactive primitive desgined for precise updates" /%}
{% /dl %}
``` 

I have  I get a can't nest a p tag. What is going on. Why does markdoc assume I intend to write a paragraph on some nodes but not others.

**Comment by louiss0** [comment]
I notice that markdoc language server doesn't provide autocomplete for built-in tags it just allows you to guess till you find one.

**Comment by rpaul-stripe** [comment]
The "Invalid attribute: 'frontmatter'" occurs because the `document` node in your `markdoc-html-tag-schemas` library appears to be missing the `frontmatter` attribute.

The `children` schema property expects an array of node types by name — it doesn't check for tags at present. The issue in the `dl` tag is that putting the `dt` and `dd` self-closing tags on the same line causes them to parse as inline tags, so they are treated as the contents of an implicit paragraph.

I can reproduce the auto-completion issue with built-in tags — I'll fix that this week. Thanks!

**Comment by louiss0** [comment]
Is there a problem with Markdoc assuming that you want to render text in a tag instead of a paragraph? I don't understand why this is a thing. In HTML text is text in a tag, not a paragraph.

**Comment by rpaul-stripe** [comment]
Unlike HTML, Markdown doesn't have any way to explicitly mark that something is a paragraph. Markdown treats any inline content that is on a line by itself as though it is nested in an enclosing block-level paragraph. Consider an example like this:

```
{% callout %}
# Test

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
{% /callout %}
```

In that example, the user would unambiguously expect that to render the two paragraphs as actual p-tag paragraphs, not just a heading followed by un-enclosed text inside of whatever tag the `callout` maps to. Now, consider an ambiguous case like the following, where it's not actually clear whether the user intends for it to be a paragraph or just text nested directly in a block-level element:

```
{% foo %}
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
{% /foo %}
```

There are cases, depending on the specific tags, where you might think that text should be a paragraph or cases where you might not. If, for example, we were to only treat the nested content inside of a tag like paragraphs when there are multiple block-level elements or something, that would still not be right all of the time, and the inconsistency would likely create more confusion. So, there's not really a good heuristic to infer it from just the syntax itself.

Of course, your schema can still control how this renders, so you can make your tag transform function peel content out of the nested paragraph tags and put it directly under the enclosing block-level tag for specific tags if that's what you want in the output. It just has to be done during rendering and not parsing.

**Comment by louiss0** [comment]
> Unlike HTML, Markdown doesn't have any way to explicitly mark that something is a paragraph. Markdown treats any inline content that is on a line by itself as though it is nested in an enclosing block-level paragraph. Consider an example like this:
> 
> ```
> {% callout %}
> # Test
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
> 
> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
> {% /callout %}
> ```
> 
> In that example, the user would unambiguously expect that to render the two paragraphs as actual p-tag paragraphs, not just a heading followed by un-enclosed text inside of whatever tag the `callout` maps to. Now, consider an ambiguous case like the following, where it's not actually clear whether the user intends for it to be a paragraph or just text nested directly in a block-level element:
> 
> ```
> {% foo %}
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
> {% /foo %}
> ```
> 
> There are cases, depending on the specific tags, where you might think that text should be a paragraph or cases where you might not. If, for example, we were to only treat the nested content inside of a tag like paragraphs when there are multiple block-level elements or something, that would still not be right all of the time, and the inconsistency would likely create more confusion. So, there's not really a good heuristic to infer it from just the syntax itself.
> 
> Of course, your schema can still control how this renders, so you can make your tag transform function peel content out of the nested paragraph tags and put it directly under the enclosing block-level tag for specific tags if that's what you want in the output. It just has to be done during rendering and not parsing.

I get this is a markdown problem thanks for the answer.  Can you please explain what the error markdoc node is.

**Comment by louiss0** [comment]
I went into the issue I found out that it was due to the fact that nodes are not imported at all. I don't know what the problem is but every time I try to use the Markdoc library I keep getting undefined. I had to copy the code of the node file to fix this library.
