### ISSUE TITLE
Typescript for Validation of Attributes

### ISSUE THREAD

**Issue by JitPackJoyride** [markdoc/markdoc#44]
I am reading the documentation and see that a large part of the validation logic for attributes is to create a Javascript object that basically has the same information that Typescript would have.

I am curious if there is a goal to create a Typescript plugin or better built-in support for Typescript? As you can imagine, writing all that code is tedious, and Typescript is a very powerful and widely adopted tool to convey that same information.

**Comment by mfix-stripe** [comment]
@JitPackJoyride the custom attribute types actually are quite different from TypeScript ones. They allow users to add a custom message for validation, which can be surfaced during linting or CI, for example. Custom attribute types also allow for custom transform functions, which let you mutate/transform the attribute value itself at runtime.

We do have plans to create a VSCode extension that can surface these validation errors in your editor (similar to what you can see here: https://markdoc.io/sandbox). 

As far as TypeScript support goes, `@markdoc/markdoc` is fully written in TypeScript, so you should be able to use the exported types to type everything you need in your application.
