### ISSUE TITLE
appDir Configuration No Longer Working in Next.js 13.5 with markdoc/next.js

### ISSUE THREAD

**Issue by thesampaton** [markdoc/markdoc#451]
### What happened?

The withMarkdoc function in the Next.js plugin has a line that references options.config.experimental.appDir to configure the appDir option. However, as of Next.js 13.5, appDir is no longer under the experimental object as it's considered a stable feature.

The offending code snippet from src/index.js:

```js
appDir:
  options.config.experimental.appDir &&
  options.defaultLoaders.babel.options.appDir
```
This causes the loader to fail because the evaluation will always return undefined.

### Expected Behavior
The nextjs plugin should work with 13.5 for both page or app router

### Workaround
In the node_modules file, i.e @markdoc/next.js/src/index.js just set appDir to true
```js
appDir: true
```

 I don't understand babel well enough to understand other side effects though hence not doing a PR to remove the check or like fixes

### To reproduce

With a working markdoc/nextjs implementation using the app directory, upgrade to NextJS 13.5.x 

### Version

0.3.2

**Comment by mfix-stripe** [comment]
@thesampaton this should be working now with `@markdoc/next.js@0.3.4`

**Comment by Alain1405** [comment]
I am using NextJS 13.5.6 without App directory and this change breaks by code. `0.3.3` version works. I suspect the reason is that `appDir` always evaluates as `true`, which is not the case since pages are still supported.
There should be a way to override this undocumented setting.

**Comment by mfix-stripe** [comment]
@Alain1405 can you push a PR that allows overriding the option?

**Comment by Alain1405** [comment]
I will have time to look into this next week.
