### ISSUE TITLE
Render image with data URI (image/svg+xml)

### ISSUE THREAD

**Issue by dpb587** [markdoc/markdoc#479]
### What happened?

Hi - I have a document with an image node that uses a data URI, specifically the `image/svg+xml` media type. The URI gets ignored and the node instead gets treated as a paragraph. If I change the media type of the data URI to, for example, `image/jpeg` it correctly becomes an image tag (although an invalid jpeg bytestream).

The only workaround I found was switching to a custom Markdoc tag. It's a reasonable workaround, but if there's a more official solution for this sort of customization I would prefer it. In my case, I'm only working with trusted content so am less concerned about validating link URIs.

Related, if it was possible for the invalid link URIs to error (rather than silent fallback to a paragraph node), it would be nice to cause some sort of build or validation error.

Thank you for taking a look at this - and for Markdoc, in general!

### To reproduce

Author an image node using a `data` URI with an `image/svg+xml` media type. Below is an example ([markdoc.dev/sandbox](https://markdoc.dev/sandbox?mode=preview&c=c3ZnK3htbCAocmVuZGVycyBhcyBgcGApCgohW2ltYWdlXShkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJR2hsYVdkb2REMGlNekFpSUhkcFpIUm9QU0l4TURBaVBqeDBaWGgwSUhnOUlqQWlJSGs5SWpFMUlpQm1hV3hzUFNKeVpXUWlQa0Z1SUZOV1J5QkpiV0ZuWlR3dmRHVjRkRDQ4TDNOMlp6ND0pCgpzdmcreG1sLCBidXQgYXMganBlZyAocmVuZGVycyBhcyBgaW1nYCkKCiFbaW1hZ2VdKGRhdGE6aW1hZ2UvanBlZztiYXNlNjQsUEhOMlp5QjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlHaGxhV2RvZEQwaU16QWlJSGRwWkhSb1BTSXhNREFpUGp4MFpYaDBJSGc5SWpBaUlIazlJakUxSWlCbWFXeHNQU0p5WldRaVBrRnVJRk5XUnlCSmJXRm5aVHd2ZEdWNGRENDhMM04yWno0PSkK))...

```markdown
svg+xml (renders as `p`)

![image](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMzAiIHdpZHRoPSIxMDAiPjx0ZXh0IHg9IjAiIHk9IjE1IiBmaWxsPSJyZWQiPkFuIFNWRyBJbWFnZTwvdGV4dD48L3N2Zz4=)

svg+xml, but as jpeg (renders as `img`)

![image](data:image/jpeg;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMzAiIHdpZHRoPSIxMDAiPjx0ZXh0IHg9IjAiIHk9IjE1IiBmaWxsPSJyZWQiPkFuIFNWRyBJbWFnZTwvdGV4dD48L3N2Zz4=)
```

### Additional context

I think the problem is that [markdown-it](https://github.com/markdown-it/markdown-it), during the tokenization, tries to validate the image link ([image.mjs](https://github.com/markdown-it/markdown-it/blob/d07d585b6b15aaee2bc8f7a54b994526dad4dbc5/lib/rules_inline/image.mjs#L38-L46))...

```
    res = state.md.helpers.parseLinkDestination(state.src, pos, state.posMax)
    if (res.ok) {
      href = state.md.normalizeLink(res.str)
      if (state.md.validateLink(href)) {
        pos = res.pos
      } else {
        href = ''
      }
    }
```

Where the default validation from [index.mjs](https://github.com/markdown-it/markdown-it/blob/d07d585b6b15aaee2bc8f7a54b994526dad4dbc5/lib/index.mjs#L23-L39) disallows most arbitrary data links (for reasonable security concerns)...

```
//
// This validator can prohibit more than really needed to prevent XSS. It's a
// tradeoff to keep code simple and to be secure by default.
//
// If you need different setup - override validator method as you wish. Or
// replace it with dummy function and use external sanitizer.
//

const BAD_PROTO_RE = /^(vbscript|javascript|file|data):/
const GOOD_DATA_RE = /^data:image\/(gif|png|jpeg|webp);/

function validateLink (url) {
  // url should be normalized at this point, and existing entities are decoded
  const str = url.trim().toLowerCase()

  return BAD_PROTO_RE.test(str) ? GOOD_DATA_RE.test(str) : true
}
```

When working directly with the markdown-it library, the link validation can be customized (or skipped entirely, ignoring security concerns) using...

```
var md = new MarkdownIt({});
md.validateLink = () => true;
```

From the Markdoc level, it seems to take full control of instantiating the markdown tokenizer in [index.ts](https://github.com/markdoc/markdoc/blob/a13cc583fa3b0420538e772a75628dd15d72b793/src/tokenizer/index.ts#L8-L16), but there is not a supported option for override or public access to apply a custom `validateLink` function.

```
  private parser: MarkdownIt;

  constructor(
    config: MarkdownIt.Options & {
      allowIndentation?: boolean;
      allowComments?: boolean;
    } = {}
  ) {
    this.parser = new MarkdownIt(config);
```

**Comment by rpaul-stripe** [comment]
You can access the MarkdownIt instance from the tokenizer and add the `validateLink` property like this:

```js
import Markdoc from "@markdoc/markdoc";

const example = `
![image](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMzAiIHdpZHRoPSIxMDAiPjx0ZXh0IHg9IjAiIHk9IjE1IiBmaWxsPSJyZWQiPkFuIFNWRyBJbWFnZTwvdGV4dD48L3N2Zz4=)
`;

const tokenizer = new Markdoc.Tokenizer();
tokenizer.parser.validateLink = () => true;

const tokens = tokenizer.tokenize(example);
const ast = Markdoc.parse(tokens);
const output = Markdoc.transform(ast, {});
const html = Markdoc.renderers.html(output);

console.log(html);
```

Or you could subclass `Markdoc.Tokenizer` and do it in an overridden constructor:

```js
class CustomTokenizer extends Markdoc.Tokenizer {
  constructor(config) {
    super(config);
    this.parser.validateLink = () => true;
  }
}
```

**Comment by mfix-stripe** [comment]
@dpb587 pushed a PR to try and fix this upstream in markdown-it: https://github.com/markdown-it/markdown-it/pull/991

**Comment by dpb587** [comment]
@rpaul-stripe -- thank you for the snippet, just verified it works. While looking through the sources, I forgot the `private` declaration property is still generally accessible in JavaScript.

@mfix-stripe -- thanks for the effort, although I don't think it's a good idea to add it as a default in markdown-it. Support of SVG does require mitigations for potential security vulnerabilities (like XSS). In the particular case of `<img src=... />` it shouldn't be a concern with browsers disallowing an execution context there. But since `validateLink` is a general-purpose function, I'd be wary that adding it would open up other SVG/XSS injection points, such as through regular links or, more likely, third-party plugins which may be relying on the function.
