### ISSUE TITLE
Code fence doesn't pass through info string

### ISSUE THREAD

**Issue by taktran** [markdoc/markdoc#480]
### What happened?

I'd like the complete info string after a code fence to be able to be passed through to my application. The Commonmark spec does allow for [info string](https://spec.commonmark.org/0.30/#info-string) and doesn't really specify what needs to be in it, however the markdoc parser only strips out the `language` part of it, and doesn't pass through the rest of it:

https://github.com/markdoc/markdoc/blob/a13cc583fa3b0420538e772a75628dd15d72b793/src/parser.ts#L67

### To reproduce

1. Create a markdoc with extra info string

~~~
```js test=true
const hello = 'yes';
```
~~~

2. Run the parser, and notice that only `js` is returned for the code fence as `language`, however `test=true` does not get passed through

### Version

0.3.5

### Additional context

I think the fix would be something along the lines of:

From https://github.com/markdoc/markdoc/blob/a13cc583fa3b0420538e772a75628dd15d72b793/src/parser.ts#L66-L71

to adding `info: token.info`

```
    case 'fence': {
      const [language] = token.info.split(' ', 1);
      return language === '' || language === OPEN
        ? { content: token.content }
        : { content: token.content, language, info: token.info };
```

and also adding `info: { type: String, render: false },` to the schema: 

https://github.com/markdoc/markdoc/blob/a13cc583fa3b0420538e772a75628dd15d72b793/src/schema.ts#L52-L58

ie, 

```
export const fence: Schema = {
  render: 'pre',
  attributes: {
    content: { type: String, render: false, required: true },
    language: { type: String, render: 'data-language' },
    info: { type: String, render: false },
    process: { type: Boolean, render: false, default: true },
  },
```

**Comment by rpaul-stripe** [comment]
Markdoc automatically parses annotations that are passed into the fence info line, so you can do:

~~~
```js {% test=true %}
...
```
~~~

And the fence AST node will have a `test` attribute with the boolean value `true`. Does that feature satisfy your use case or do you still want to get the raw info line?

**Comment by taktran** [comment]
Amazing @rpaul-stripe - that is exactly what I need. Thanks a bunch! 🎉
