### ISSUE TITLE
Markdoc `module.exports` pattern not working with Next.js `14.1.0`

### ISSUE THREAD

**Issue by ReeceHumphreys** [markdoc/markdoc#482]
### What happened?

When using markdoc it is common to have a file to export a single markdoc tag. For example `markdoc/tags/step.markdoc.ts`:

```ts

import { Tag, Node, Config } from '@markdoc/markdoc';

export const step = {
  render: 'Step',
  attributes: {
    title: {
      type: String
    },
   ...
  },
```

It also seems semantic to then have a `markdoc/tags/index.ts` file to re-export all of the tags from these different files with potentially fixed or different casing to enable kebab casing inside of the markdown files:

```ts

import { step } from './step.markdoc';

module.exports['step'] = step;
```

However, with Next.js 14.1.0 it seems this pattern is no longer working. I am unsure if this is a bug with Next.js or if this pattern should no longer be used:

```
Server Error
TypeError: Cannot set properties of undefined (setting 'step')
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
markdoc/tags/index.ts (19:22) @ eval
  18 |
> 19 | module.exports['step'] = step;
```

If this is instead switched to using `export` instead of `module.exports` everything works.

```
export { step }
```

However this is not an ideal solutions for handling the renaming of exports to kebab case. For example

``` ts
module.exports['mini-card'] = miniCard; // Valid js
export { ... }; // No nice way to export miniCard as mini-card
```

 

### To reproduce

Shown above

### Version

0.4.0

**Comment by mfix-stripe** [comment]
Thanks for reporting @ReeceHumphreys. Seems like this definitely could be on the `next` side of things, maybe in them changing a core dependency or something (e.g. Babel?). 

If you have the chance, would greatly appreciate you looking into a solution for this in our `@markdoc/next.js` library—a good place to start is the [`loader`](https://github.com/markdoc/next.js/blob/main/src/loader.js), which calls this [`defaultObject`](https://github.com/markdoc/next.js/blob/main/src/runtime.js#L56-L59) function.

**Comment by ReeceHumphreys** [comment]
Hi @mfix-stripe , I am actually not using the `@markdoc/next.js` library. I am eventually just calling `Markdoc.parse` and friends which rules that the loader as the problem.

What is stranger about this issue is I have been unable to reproduce it with a simple Next.js starter either. It seems to be that the issue is that `module.exports` itself is undefined.

**Comment by mfix-stripe** [comment]
@ReeceHumphreys that seems like it could be a problem in Next itself?

Also for your particular use case above, instead of `module.export['step']` you could do:

```js
export const step = ...
```

**Comment by ReeceHumphreys** [comment]
Closing this issue since this is definitely more of a Next.js issue. However the solution given for `step` will not work for things like `module.exports['mini-card']` since you cannot do:

```js
export const mini-card = ...
```

This prevents you from defining custom markdoc tags containing hyphens. Our solution was just to use the syntax that @mfix-stripe suggested and to rename any tags that were using hyphens.

**Comment by mfix-stripe** [comment]
Thanks @ReeceHumphreys. Please follow up here if you resolve the Next.js issue—I'm curious myself.
