### ISSUE TITLE
`transform` should work with Promises but doesn't

### ISSUE THREAD

**Issue by alvinometric** [markdoc/markdoc#487]
### What happened?

Hello! 

I might not have the perfect vocabulary, but according to the [types here](https://github.com/markdoc/markdoc/blob/60a2c831bd7ac8f2f24aabfde0b36e56e5d0dbe1/src/types.ts#L107), the `transform` method of a custom tag should accept a promise. Right now it doesn't.

```js
const image = {
  ...nodes.image,
// this should work
  transform: async (node, config) => {
    const attributes = node.transformAttributes(config);
    const children = node.transformChildren(config);

    await sleep(100);

    return new Tag('img', attributes, children);
  },
};
```

### To reproduce

I made a reproduction with this stackblitz project: https://stackblitz.com/edit/stackblitz-starters-mm5yd1?file=index.js

According to the docs, this should work (run `node index.js`) with the promise but it doesn't.

Removing the promise in the Stackblitz will make the code work.

### Version

0.4.0

**Comment by rpaul-stripe** [comment]
In your stackblitz example, it looks like you are missing an `await` keyword in front of the transform function. As written, the `content` variable in your example that gets passed into the HTML renderer is an unresolved promise, which the renderer doesn't know how to handle.

Your example works as expected if you change the transform line to this: `let content = await Markdoc.transform(ast, config);`

**Comment by alvinometric** [comment]
Oh, that makes sense! Thanks Ryan for the speedy reply
