### ISSUE TITLE
Website landing hero is invisible

### ISSUE THREAD

**Issue by mbeaudru** [markdoc/markdoc#513]
### What happened?

<img width="1189" alt="image" src="https://github.com/markdoc/markdoc/assets/8942633/095b902a-c4ec-4d84-b6d7-697fd1c06742">

### To reproduce

Go to [markdoc.dev](https://markdoc.dev/) and observe the problem

It happens because the hero text is in display none

![image](https://github.com/markdoc/markdoc/assets/8942633/cfc7e438-997a-44ce-ab83-c309e22f0971)

Without this class, it works as expected

<img width="1437" alt="image" src="https://github.com/markdoc/markdoc/assets/8942633/a48e491d-c02e-4db3-a1fb-e977e2e2c48d">

### Version

latest

**Comment by mfix-stripe** [comment]
https://github.com/markdoc/docs/commit/c3f7966dab523221a1cec27c9672877afcd9eea4
