### ISSUE TITLE
Curly braces inside fenced code blocks get interpreted as tags

### ISSUE THREAD

**Issue by theletterf** [markdoc/markdoc#530]
### What happened?

I've added curly braces to document some Jinja syntax for SQL. I had to escape the characters to avoid the code block render as a tag. Is there a way to avoid or alter that behavior?

### To reproduce

1. Create a Markdoc document.
2. Add a fenced code block.
3. Put  `{% if defined(filters) %}` inside the code block.
4. Build the site.

### Version

^0.4.0

### Additional context

We use NextJS

**Comment by matv-stripe** [comment]
Hi @theletterf ! You should be able to add the `process=false` annotation to the code block:


~~~~
``` {% process=false %}
{% if defined(filters) %}
```
~~~~

**Comment by theletterf** [comment]
@matv-stripe Nice! Is there a way of enabling that behavior by default?

**Comment by mfix-stripe** [comment]
@theletterf you can update your `nodes.code` config to set the `process` attribute to `false` by default 👍 

https://github.com/markdoc/markdoc/blob/main/src/schema.ts#L57
