### ISSUE TITLE
Typo in docs site code example

### ISSUE THREAD

**Issue by davidyeiser** [markdoc/markdoc#62]
### What happened?

In the [Parse section](https://markdoc.io/docs/render#parse) of the **Phases of rendering** page, the code example for walking through the AST nodes looks like this:

```
const ast = Markdoc.parse(document);

for (const node of document.walk()) {
  // do something with each node
}
```

I believe `.walk()` should be called on `ast` instead, like so:

```
const ast = Markdoc.parse(document);

for (const node of ast.walk()) {
  // do something with each node
}
```

### To reproduce

See code example above

**Comment by mfix-stripe** [comment]
Ah yes, this was fixed here @davidyeiser https://github.com/markdoc/docs/commit/1d1d2d5e839ad59bc03a2b379b01f58f6258ce64
