### ISSUE TITLE
Footnotes?

### ISSUE THREAD

**Issue by igbanam** [markdoc/markdoc#74]
As a writer, I'd like to be able to use footnotes to add supporting context to the content I'm writing. Can we have footnote support in Markdoc?

Usually, when adding supporting context to a sentence, one would use the em-dash "—" to denote a momentary break in thought, a somewhat tangential drift. When this _drift-break_ exceeds some arbitrary attention quota — would be nice to get empirical data on this — the drift breaks the reader's experience. The go-to solution for this is a footnote.

The footnote syntax is detailed in the [Markdown Guide's Extended Syntax](https://markdownguide.org/extended-syntax/#footnotes)

**Comment by mfix-stripe** [comment]
@igbanam This is a duplicate issue of https://github.com/markdoc/markdoc/issues/70. 

I will reopen that issue for further discussion—could you please share these ideas over there? 🙂
