### ISSUE TITLE
Allow using variables for link hrefs

### ISSUE THREAD

**Issue by kemmerer** [markdoc/markdoc#87]
### What happened?

# What I'm trying
I'm trying to use a variable to populate a link. More complete example below, but something like:

`'[Link]({% $linkVariable %})'`

# What I'd expect
I'd expect that the end result is a link element pointing to `linkVariable`.

e.g. If `$linkVariable` is "https://markdoc.io", something like:
`<a href="https://markdoc.io">Link</a>`

# Actual result
Instead the resulting output is:
```
[Link](https://markdoc.io/)
```
That's the **rendered output** from `Markdoc.renderers.react()`, not an intermediary step which gets parsed further.

# Question
Or maybe there's some other way of handling this? I'll probably create a custom tag in the meantime, but I'm not sure if it's expected that Markdoc should handle a variable in this way or not.

PS. Thanks for releasing Markdoc!

### To reproduce

I started with a create-react-app output, and then replaced **App.js** with:

```jsx
import Markdoc from '@markdoc/markdoc';
import React from 'react';

function App() {
  const md = [
    '- [Link 1](https://markdoc.io/)',
    '- [Link 2]({% $linkVariable %})',
  ].join('\n');

  const ast = Markdoc.parse(md);
  const content = Markdoc.transform(
    ast,
    {
      variables: {
        linkVariable: 'https://markdoc.io/',
      },
    },
  );

  return (
    <div className="App">
      {Markdoc.renderers.react(content, React, {  })}
    </div>
  );
}

export default App;
```

The output is:

```
* Link 1
* [Link 2](https://markdoc.io/)
```
Where "Link 1" is a proper link and the 2nd line looks like that output verbatim. It prints the markdown, not the rendered markdown. 

### Version

0.1.2

### Additional context

# Possible Test Case

I added the following to `src/parser.test.ts`

```javascript
+    it('in a link', function () {
+      const example = convert(`
+      [foo]({% bar %})
+      `);
+
+      expect(example).toDeepEqualSubset({
+        type: 'document',
+        children: [
+          {
+            type: 'paragraph',
+            children: [
+              {
+                type: 'inline',
+                children: [
+                  {
+                    type: 'link',
+                    attributes: { href: new Variable(['bar'], null) },
+                    children:  [{
+                      type: 'text',
+                      attributes: { content: 'foo' },
+                    }],
+                  },
+                ],
+              },
+            ],
+          },
+        ],
+      });
+    });
+
```

# markdown-it

It seems to me that this occurs because of the way `markdown-it` does the parsing. Because the parsing comes before Markdoc's own variable substitution, I'm not sure if this is something that's actually addressable.

**Comment by matv-stripe** [comment]
Hi @kemmerer ! Thank you for the detailed report

In stripe.com/docs to solve this we have a custom `link` tag which allows us to do `{% link href=$variable %}Link{% /link %}` . We intentionally use this tag infrequently because we try to enforce fully static links so we can perform broken link detection.

Like you mentioned, this issue occurs based on how `markdown-it` is parsing out the contents.

**Comment by mfix-stripe** [comment]
@kemmerer this is currently working as intended, so I changed your issue from a bug to an enhancement 🙂.  

Not sure if we want to support this or not yet, because it creates complications in the language semantics for of how variables are applied. 

That said, you can always use the work-around @matv-stripe described above^ 🙂

Hope that helps!

**Comment by kemmerer** [comment]
Ah, great! Thanks @matv-stripe and @mfix-stripe.

The workaround works well enough for my purposes.

It might be better off documenting the variable substitution constraints rather than trying to figure out how to make it work for the enhancement. (e.g. adding the custom link tag to the FAQ or something along those lines.)

**Comment by mfix-stripe** [comment]
> It might be better off documenting the variable substitution constraints rather than trying to figure out how to make it work for the enhancement. (e.g. adding the custom link tag to the FAQ or something along those lines.)

I dig this idea.

**Comment by mfix-stripe** [comment]
Deployed here: https://markdoc.io/docs/variables#caveats
