### ISSUE TITLE
Attempted import error when deploying to vercel

### ISSUE THREAD

**Issue by febriliankr** [markdoc/markdoc#88]
### What happened?

Attempted import error: '/vercel/path0/markdoc/tags/index.ts' does not contain a default export (imported as 'tags'). Also unable to deploy to vercel

### To reproduce

Clone this repository and npm run build/yarn build

### Version

0.1.2

**Comment by febriliankr** [comment]
Yes I used that repo.

I'm using MacOS Monterey 12.0.1 (21A559). I don't think the issue is in my machine cause vercel build process also showed that message. Thank you

**Comment by mfix-stripe** [comment]
@febriliankr I see that message locally, but it is just a warning, and should be benign. I am able to deploy the repo despite the warning message: https://markdoc-starter-stripe-oss-stripe-dev.vercel.app.

Can you try redeploying with `npx vercel --force`?

**Comment by mfix-stripe** [comment]
Closing w/ above fix. Please open a new issue with steps to reproduce if something comes up.
