### ISSUE TITLE
Fails to compile in Angular 12

### ISSUE THREAD

**Issue by jamesmandrews** [markdoc/markdoc#9]
### What happened?

After installing Markdoc in a new angular 12 app, I get the following error.

```
Error: node_modules/@markdoc/markdoc/dist/index.d.ts:104:48 - error TS2694: Namespace '"/Users/jandrews/Projects/md/node_modules/@markdoc/markdoc/dist/src/types"' has no exported member 'Function'.

104         Function: typeof import("./src/types").Function;
```

### To reproduce

1) Install Angular 12.
2) Create new project `ng new markdoc-test`
3) Install markdoc `npm install @markdoc/markdoc`
4) Install dependencies `npm i --save-dev @types/react` and `npm i --save-dev @types/markdown-it`
5) Run Angular `ng serve --ssl`

The server will start and fail with:

```
Error: node_modules/@markdoc/markdoc/dist/index.d.ts:104:48 - error TS2694: Namespace '"/Users/jandrews/Projects/md/node_modules/@markdoc/markdoc/dist/src/types"' has no exported member 'Function'.

104         Function: typeof import("./src/types").Function;
```

The problem seems to be `Function` isn't exported, and since it's imported in, it can't be exported with export statement.  I had edited `types.d.ts` to include `export class astFunction extends Function {}` and then the `index.ts` file on line 104 to use `        Function: typeof import("./src/types").astFunction;` instead, and that prevented the compile error.  Not sure if there is a better fix, but I thought I'd mention this here. 

### Version

^0.1.1

**Comment by mfix-stripe** [comment]
Thanks @jamesmandrews, looking into this. `Function` is exported from `dist/src/types.d.ts`, so I think this is a TypeScript "bug". Will dig in deeper here.

**Comment by jamesmandrews** [comment]
Just confirming this did indeed resolve the bug, thanks for your prompt fix.
